### 
# MkDocs Configuration File.
# 
# To build these docs, change to base of repository and run `mkdocs build` and
# docs will be build into site_dir variable value in this file.
# 
# Alternatively, there is a script in the `scripts` folder for convenience.
### 
site_name: fpdf2
site_url: https://pyfpdf.github.io/fpdf2/
repo_url: https://github.com/PyFPDF/fpdf2
site_description: fpdf2 - minimalist PDF creation library for Python
docs_dir: docs/
site_dir: public/
use_directory_urls: false
edit_uri: edit/master/docs
theme:
  name: material
  custom_dir: docs/overrides/
markdown_extensions: [toc, pymdownx.highlight, pymdownx.superfences]
plugins:
  - include-markdown
  - search
  - with-pdf:  # https://github.com/orzih/mkdocs-with-pdf
      output_path: fpdf2-manual.pdf
      cover_title: fpdf2 manual
      cover_subtitle: A minimalist PDF creation library for Python
      author: ' '
      copyright: ' '
      #cover: false
      #back_cover: true
      #custom_template_path: TEMPLATES PATH
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #exclude_pages:
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #two_columns_level: 3
      #render_js: true
      #headless_chrome_path: headless-chromium
      #enabled_if_env: ENABLE_PDF_EXPORT
      #debug_html: true
      #show_anchors: true
      #verbose: true
nav:
- 'Project Home':                   'index.md'
- 'Tutorial':                       'Tutorial.md'
- 'Existing PDFs':                  'ExistingPDFs.md'
- 'HTML':                           'HTML.md'
- 'Images':                         'Images.md'
- 'Links':                          'Links.md'
- 'Tables':                         'Tables.md'
- 'Layout':
  - 'Page format and orientation':  'PageFormatAndOrientation.md'
  - 'Margins':                      'Margins.md'
  - 'Page breaks':                  'PageBreaks.md'
- 'Document outline & table of contents': 'DocumentOutlineAndTableOfContents.md'
- 'Text styling':                   'TextStyling.md'
- 'Presentations':                  'Presentations.md'
- 'Annotations':                    'Annotations.md'
- 'Shapes':                         'Shapes.md'
- 'Maths':                          'Maths.md'
- 'Drawing':                        'Drawing.md'
- 'SVG':                            'SVG.md'
- 'Barcodes':                       'Barcodes.md'
- 'Metadata':                       'Metadata.md'
- 'Logging':                        'Logging.md'
- 'Templates':                      'Templates.md'
- 'Unicode':                        'Unicode.md'
- 'Emojis, Symbols & Dingbats':     'EmojisSymbolsDingbats.md'
- 'Web2Py':                         'Web2Py.md'
- 'API':                            'https://pyfpdf.github.io/fpdf2/fpdf/'
- 'Development':                    'Development.md'
- 'FAQ':                            'FAQ.md'
